### ISSUE TITLE
add --output option for writing to file via argument option

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeometa#10]
cc @alexandreleroux 

By default pygeometa writes to `stdout`.  Add `--output` parameter which writes to specified file.  This allows for catching errors and exiting gracefully without shell redirecting.

**Comment by tomkralidis** [comment]
Implemented.  Default behaviour exists.  If `--output` is passed, file written to `stdout`.

@alexandreleroux can you update the docs?

**Comment by tomkralidis** [comment]
oops, duplicate of #9

**Comment by alexandreleroux** [comment]
Hi Tom, it failed running properly with --output. I got errors... I'll followup by email
