### ISSUE TITLE
"AttributeError: 'str' object has no attribute 'items'" when reading in a custom .yml file

### ISSUE THREAD

**Issue by geofbaum** [geopython/pygeometa#109]
Hello,

Not sure if this issue is specifically with pygeometa or if there is another issue somewhere in my workflow. I'm working to create metadata files for all of my companies geospatial data. As a test, I created a test yaml file based on the sample one from this repository, and updated it with information pertinent for my use.  Pygeometa works fine and creates an xml file if I have everything hardcoded into that yaml file. 

However, I had hoped to be able to update the yaml on the fly as I go through the data files so that I can update it with the extent information, file type (vector, grid, or something else) and other information based on the file. When I do this, I can update the yaml file as expected and save it to be able to be used by pygeometa. If I do this though, I recieve the error as mentioned in the title above. So once again, if I manually update my yaml file and save it and use pygeometa it works but if I try to do it on the fly it does not. Any help would be useful if anyone can see something in my code that would be cause this issue to arise. Thanks in advance.

System: Win7
Env: JupyterLab notebook for testing
Python Version: 3.6.6

```python
import yaml
from osgeo import gdal, ogr, osr
import datetime
import os
from pygeometa.core import render_template

path = "path_to_my_geospatial_data"

# Then I grab a bunch of the information about the geo datafile to input into my *.yml file

# Next open the basic file
with open("test.yml") as f:
     data = yaml.load(f)

# change values in data to account for the information I got from the geo datafile

# Now save to a new temporary .yml file
with open("test_new.yml", "w") as ff:
    yaml.dump(data, ff)
    
ff.close()

# Finish with giving the new .yml file to pygeometa to create the metadata xml
xml_string = render_template("test_new.yml", schema='iso19139')
with open('test_new.xml', 'w') as x:
    x.write(xml_string)
```

**Comment by tomkralidis** [comment]
@geofbaum thanks for the report.  I am unable to reproduce.  The following works for me:

```python
import yaml

from pygeometa.core import render_template

with open('sample.yml') as fh:
    d = yaml.load(fh)

    print(d['identification']['title_en'])

    print(render_template(d, schema='iso19139'))

    d['identification']['title_en'] = 'another title'

    print(d['identification']['title_en'])

    print(render_template(d, schema='iso19139'))
```

**Comment by geofbaum** [comment]
@tomkralidis Thanks for your reply, when I copy and paste your code into the same JupyterLab it works even with me subbing out 'another title' for the extracted title that I was attempting to use before. So there's something going on I assume somewhere with my code. I'll start adding each section that I want to change to your example code line by line and see where the issue is coming from and report back.

Thanks again.

**Comment by geofbaum** [comment]
Well I found it, and it's my error and my fault for not triple checking my code. I was passing a url value in the distribution section directly to a url section like ```d['distribution']['url']``` and not to a section like ```d['distribution']['wms']['url']```. Sorry again @tomkralidis !

**Comment by tomkralidis** [comment]
@geofbaum all good - thanks for following up and good luck!
