### ISSUE TITLE
SyntaxWarning on import

### ISSUE THREAD

**Issue by epifanio** [geopython/pygeometa#118]
reporing a warning -
Testing a pip-installed version of `pygeometa` I got a warning at the import - on `python-3.8.2`:

```python
import pygeometa
/usr/lib/python3.8/site-packages/pygeometa/core.py:77: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if 'language_alternate' is None:  # noqa unilingual
```

**Comment by tomkralidis** [comment]
@epifanio thanks for the report.  Fixed in #119.  Can you validate?
