### ISSUE TITLE
crs input formats support

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#12]
Documentation specify that the CRS needs to be an 'EPSG code identifier'. Can pygeometa ingest anything else at the moment? Can it ingest OGC WKT directly? If not, should this be a feature request? Thanks -- Alex

**Comment by tomkralidis** [comment]
@alexandreleroux the MCF `spatial.crs` value simply gets passed into, for example, https://github.com/geopython/pygeometa/blob/master/pygeometa/templates/iso19139/main.j2#L112.  So you can specify WKT and it will display in the output XML but with EPSG as the qualifier, which would be incorect.  We can open a feature request if this is desired.

**Comment by alexandreleroux** [comment]
Thanks Tom. If the need for supporting WKT directly gets confirmed, I'll add a feature request. No further actions required at this point. Thanks -- Alex
