### ISSUE TITLE
Add capability to add/edit wmdr:observation information

### ISSUE THREAD

**Issue by ejwelton** [geopython/pygeometa#123]
Various templates exist for WMDR elements, but observation is currently excluded. The OSCAR API requires at least one observation for each programAffiliation. To fully utilize pyoscar for uploading XML an observation template would be required.

**Comment by thineshsornalingam** [comment]
Hi Tom,

Per our discussion, recording it here: 

We also got the same request from Government of British Columbia who would like to upload/update sensor and observed variable. Just adding to the interest in this feature.

Thank you
Thinesh S.

**Comment by tomkralidis** [comment]
Implemented in #141
