### ISSUE TITLE
enable a STAC export of mcf

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#125]
As suggested in https://github.com/geopython/pygeoapi/pull/563#discussion_r515714896 provide a mechanism to export a mcf as a metadata document describing a STAC-item (encoded in yml)

STAC item spec is defined at https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#stac-common-metadata

**Comment by tomkralidis** [comment]
As discussed in #130 perhaps MCF is more aligned to the STAC collection spec.  Having said this, there's no reason we can't support both levels of granularity depending on the workflow. @pvgenuchten thoughts?

**Comment by tomkralidis** [comment]
implemented in #130
