### ISSUE TITLE
Pin requirements to stable versions

### ISSUE THREAD

**Issue by gamesbook** [geopython/pygeometa#126]
Is it possible to pin requirements to stable versions of dependencies?  Jinja2 for example, has a 3.0.0alpha that now gets installed whereas it would be better to use the stable 2.11.2 release.  We need to be able to install a version of pygeometa that still runs under Python 2.7.

**Comment by tomkralidis** [comment]
Running `pip install jinja2 -U` installs 2.11.2.  The [current listing on PyPI](https://pypi.org/project/Jinja2/) also shows 2.11.2.

As well, pygeometa dropped Python 2 support [some time ago](https://github.com/geopython/pygeometa/pull/113).

**Comment by gamesbook** [comment]
Thanks Tom (yes, I was being very optimistic about the Python 2 part).
