### ISSUE TITLE
support HNAP distribution language implementation

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#15]
Feature request for the support of the HNAP schema, specifically the implementation of language in HNAP which doesn't use `gmd:language` but rather uses `xlink:role` for specifying language.

Possible implementation (not from me) proposes supporting tokens such as `[distribution:wms:eng-CAN]` and `[distribution:wms:fra-CAN]`, thus if there's three tokens (1:2:3), pygeometa can output the last token as `xlink:role`

**Comment by tomkralidis** [comment]
@alexandreleroux added in 4eb50e4ec7a5ce48225ff61364dd16b5cbf8324f.  You **may** want to document this somewhat for HNAP support.  I will say this is an exotic implementation of `xlink:role` as part of ISO.  ISO has numerous places to articulate language already

**Comment by alexandreleroux** [comment]
Thanks for the implementation @tomkralidis ! I'm running into issues validating HNAP xml outputs from the latest pygeometa. I'll log as individual issues when appropriate
