### ISSUE TITLE
Generate xml string (render_j2_template) got an error

### ISSUE THREAD

**Issue by aijogja** [geopython/pygeometa#157]
I use this sample mcf https://github.com/geopython/pygeometa/blob/master/sample.yml

when I run `pygeometa metadata generate path/to/file.yml --schema=iso19139` I got an error `jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'main'`

**Comment by aijogja** [comment]
I run the [run_tests.py](https://github.com/geopython/pygeometa/blob/master/tests/run_tests.py) also got a similar error.

**Comment by tomkralidis** [comment]
Thanks for the report.  Which version of pygeometa are you using?

**Comment by tomkralidis** [comment]
Note: if you are downloading from PyPI, pygeometa was updated today to 0.9.0 and test again.

**Comment by aijogja** [comment]
I used pygeometa 0.8.0.
Okay, I will try to update it to 0.9.0.
Thank you Tom

**Comment by aijogja** [comment]
It works.
Thanks Tom
