### ISSUE TITLE
Tagging current pygeometa version as 0.1.0 on GitHub

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#17]
Does it make sense to tag the current pygeometa version on GitHub as 0.1.0? It currently has no version number and this is annoying when trying to reference to a pygeometa version. Furthermore, pygeometa's output currently includes:

`<gco:CharacterString>This metadata record was generated by pygeometa-0.1.0 (https://github.com/geopython/pygeometa)</gco:CharacterString>`

It specifically states 0.1.0, so it would make sense that this value is in sync with release tags in the code repository. Makes sense? Thanks! -- Alex

**Comment by tomkralidis** [comment]
@alexandreleroux good point. Let's tackle the current outstanding issues and cut a 0.2.0 release.

**Comment by tomkralidis** [comment]
Version 0.1.0 tagged.
