### ISSUE TITLE
use of json arays in yaml

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#174]
for keywords and bounding box the json syntax is used inside yaml

https://github.com/geopython/pygeometa/blob/253a78fdd4594df0dbce127d3d3c1b2407511897/sample.yml#L53

This presents challenges for example in case I use yaml.dump to serialise a python object to disk as yaml

I wonder why the array are not encoded as yaml, eg

```yaml
    - bbox: 
      - -8.0333333
      - 49.233343899999994
      - 2.8333224999999995
      - 59.8333333
```

**Comment by tomkralidis** [comment]
@pvgenuchten what are the resulting issues/challenges?  Either approach is valid YAML, AFAICT.

**Comment by pvgenuchten** [comment]
ok clear, no further issues identified, just for clarification

so closing...
