### ISSUE TITLE
Date requirements for HNAP 2.3

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#18]
Request for the adjustment of pygeometa's HNAP XML output for dates. As of HNAP 2.3, *both* publication and creation dates are mandatory (with their respective 'Date Type').

In a pygeometa MCF file, in the [identification] section, if I provide:
    date=1991-03-12T00:00:00Z
    datetype=publication
    date=1996-01-01T00:00:00Z
    datetype=creation
the first date is ignored (probably overwritten by the second one).

A potential solution would be to, in MCF files, specifying dates with parameters such as:
    creationdate=value
    publicationdate=value
A creationdate parameter in an MCF would create both the date and datetype in the XML.

Better ideas? Thanks -- Alex

**Comment by tomkralidis** [comment]
Fixed in master branch via #27.  @alexandreleroux can you  update docs?  We now use `creation_date`, `publication_date`, and `revision_date` and no longer use `date` or `datetype`.

**Comment by alexandreleroux** [comment]
updated documentation accordingly, closing ticket, thanks :-)
