### ISSUE TITLE
Error in the creation of discovery metadata

### ISSUE THREAD

**Issue by maixino** [geopython/pygeometa#188]
Dear All,
I would like to create discovery metadata from my xml files that I converted to yaml with the pygeometa project when I type the command wis2box metadata discovery publish $WIS2BOX_DATADIR/metadata/discovery/MD_2M_TempM.yml
I get this error message : Setting up logger with level: INFO
/usr/local/lib/python3.9/site-packages/elasticsearch-7.17.7-py3.9.egg/elasticsearch/connection/base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security.
warnings.warn(message, category=ElasticsearchWarning)
Publishing discovery metadata from /data/wis2box/metadata/discovery/MD_2M_TempM.yml
[2022-11-06T05:59:55Z] {/usr/local/lib/python3.9/site-packages/pygeometa/core.py:308} INFO - MCF version: 1.0
Error: 'begin'
Can anyone help me?

**Comment by maixino** [comment]
[Climate and health Bulletin.zip](https://github.com/geopython/pygeometa/files/9997698/Climate.and.health.Bulletin.zip)

**Comment by tomkralidis** [comment]
Hi @maixino.  Looks like you are running this in the context of [wis2box](https://github.com/wmo-im/wis2box) workflow.

I've isolated/reproduced per below:

```bash
(pygeometa) (base) tomkralidis@aruba:~/Dev/pygeometa/pygeometa$ pygeometa metadata generate ~/Desktop/Climate.and.health.Bulletin/MD_2M_TempM.yml --schema oarec-record
Traceback (most recent call last):
  File "/Users/tomkralidis/Dev/pygeometa/bin/pygeometa", line 11, in <module>
    load_entry_point('pygeometa==0.13.1', 'console_scripts', 'pygeometa')()
  File "/Users/tomkralidis/Dev/pygeometa/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tomkralidis/Dev/pygeometa/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/tomkralidis/Dev/pygeometa/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tomkralidis/Dev/pygeometa/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tomkralidis/Dev/pygeometa/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tomkralidis/Dev/pygeometa/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tomkralidis/Dev/pygeometa/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/tomkralidis/Dev/pygeometa/lib/python3.7/site-packages/pygeometa-0.13.1-py3.7.egg/pygeometa/core.py", line 524, in generate
    content = schema_object.write(mcf_dict)
  File "/Users/tomkralidis/Dev/pygeometa/lib/python3.7/site-packages/pygeometa-0.13.1-py3.7.egg/pygeometa/schemas/ogcapi_records/__init__.py", line 127, in write
    begin = mcf['identification']['extents']['temporal'][0]['begin']
KeyError: 'begin'
```

In your MCF, I see the following:

```yaml
temporal:
- {}
```

Given there is no temporal information, do not include the `temporal` property.

Following this, running the MCF again, there are a few errors that require updating:

1. Add `spatial` section:

```yaml
spatial:
    datatype: vector
    geomtype: point
```

2. In the `metadata` section, add:
```yaml
   language: en
   charset: utf-8
```

3. In the `identification` section, add/update as follows:
```yaml
    status: null
    fees: None
    url: https://example.org
    maintenancefrequency: onGoing
````

4. In the `metadata` section, set `'1.0'` to a number, not a string (so `1.0`)

5. In your `contact` section, set values that are `null` to `None`, or try to fill with the appropriate values.

6. In your `distribution.link-0` section, set values that are `null` to `None`, or try to fill with the appropriate values.


An example with the above mentioned changes can be found below.

```yaml
contact:
    pointOfContact:
        address: ACMAD Niger
        administrativearea: Niamey Urban Community
        city: Niamey
        country: Niger
        email: contact@acmad.org
        fax: None
        individualname: DIT/DVP/DCE
        organization: ACMAD
        phone: None
        positionname: None
        postalcode: '13184'
        url: www.acamd.org
distribution:
    link-0:
        description: DCPC-ACMAD
        function: download
        name: Permanent link
        type: WWW:LINK-1.0-http--link
        url: http://sgbd.acmad.org:8080/thredds/catalog.html?urn=urn:x-wmo:md:acmad::2M
#            TempM
spatial:
    datatype: vector
    geomtype: point

identification:
    abstract: This product shows the means of 2 meter temperature over Africa.
    accessconstraints: copyright
    extents:
        spatial:
            - bbox:
                - -30.0
                - -40.0
                - 70.0
                - 40.0
    dates:
        creation: 2022-11-11
    keywords:
        keywords-0:
            keywords:
            - Meteorological geographical features
            type: null
        keywords-1:
            keywords:
            - meteorology
            - climatology weatherForecasts
            - synopticMeteorology
            type: theme
        keywords-2:
            keywords:
            - OriginatingCentre
            type: dataCentre
        keywords-3:
            keywords:
            - u-component of wind
            - relative humidity
            - Temperature
            type: null
    status: onGoing
    fees: None
    url: https://example.org
    maintenancefrequency: asNeeded
    rights: None
    title: Near surface air mean temperature
    topiccategory:
    - climatologyMeteorologyAtmosphere
mcf:
    version: 1.0
metadata:
    datestamp: '2022-05-08T14:21:21Z'
    hierarchylevel: series
    identifier: urn:x-wmo:md:acmad::2M TempM
    language: en
    charset: utf-8
```

**Comment by maixino** [comment]
Hi Tom,
Thank you very much for your reply, I'll try and get back to you.

**Comment by tomkralidis** [comment]
Sounds good @maixino.  Note the reference documentation for MCF can be found on the [pygeometa](https://geopython.github.io/pygeometa/reference/mcf) website.

**Comment by maixino** [comment]
to generate my yml files, I used the commands found on your github https://github.com/geopython/pygeometa

**Comment by maixino** [comment]
Hi All,
How to make them available on WIS, i.e. display them?
Best regards

**Comment by tomkralidis** [comment]
Hi @maixino this repository is specifically for pygeometa.  The [wis2box](https://github.com/wmo-im/wis2box) software uses pygeometa.  Any wis2box related questions should be directed to the wis2box GitHub repository.
