### ISSUE TITLE
Support for multilingual Identification-URL

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#21]
In a pygeometa MCF file, we must specify the Identification 'url' parameter. We cannot currently specify different URLs for different languages. At least for HNAP, pygeometa stores this information in the output XML as gmd:supplementalInformation. However, for HNAP, this information needs to be provided in the output XML in both language.

Currently, pygeometa generates:
```
      <gmd:supplementalInformation>
        <gco:CharacterString>http://weather.gc.ca/grib/grib2_glb_25km_e.html</gco:CharacterString>
      </gmd:supplementalInformation>
```

and the following is expected:
```
                        <gmd:supplementalInformation xsi:type="gmd:PT_FreeText_PropertyType">
                                <gco:CharacterString>http://weather.gc.ca/grib/grib2_glb_25km_e.html</gco:CharacterString>
                                <gmd:PT_FreeText>
                                        <gmd:textGroup>
                                                <gmd:LocalisedCharacterString locale="#fra">http://weather.gc.ca/grib/grib2_glb_25km_f.html</gmd:LocalisedCharacterString>
                                        </gmd:textGroup>
                                </gmd:PT_FreeText>
                        </gmd:supplementalInformation>
```

One possibility would be to support url_en and url_fr in MCF files. If no url_en or url_fr exists, then url is used. This would allow specifying language-specific URLs in pygeometa MCF files.

Let me know if you need any additional info. Thanks -- Alex

**Comment by tomkralidis** [comment]
Fixed in master in #30 .  If `identification.url` exists, output single language.  Else output `identification.url_en` and `identification.url_fr`.  @alexandreleroux: can you update docs?

**Comment by alexandreleroux** [comment]
I confirm solution works. Thanks! Will close ticket after updating docs.

**Comment by alexandreleroux** [comment]
Closing, added doc on commit 0027b093c65fd09d3cc6f95971029187d736baf5 ... that said, we do need cleaning multilanguage (code+doc) as stated in #33
