### ISSUE TITLE
check thesaurus import from iso19139

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#225]
quite some inspire metadata these days uses following syntax to indicate a thesaurus, this is not picked up by owslib/pygeometa at iso19139 import

```
<gmd:thesaurusName>
            <gmd:CI_Citation>
              <gmd:title>
                <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/theme">GEMET - INSPIRE themes, version 1.0</gmx:Anchor>
              </gmd:title>
              <gmd:date>
                <gmd:CI_Date>
                  <gmd:date>
                    <gco:Date>2008-06-01</gco:Date>
                  </gmd:date>
                  <gmd:dateType>
                    <gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication"/>
                  </gmd:dateType>
                </gmd:CI_Date>
              </gmd:date>
            </gmd:CI_Citation>
          </gmd:thesaurusName>
```

**Comment by tomkralidis** [comment]
@pvgenuchten can you provide a full sample ISO record?

**Comment by pvgenuchten** [comment]
Some examples: 
- https://nationaalgeoregister.nl/geonetwork/srv/metadata/208bc283-7c66-4ce7-8ad3-1cf3e8933fb5/formatters/xml
- https://inspire-geoportal.ec.europa.eu/resources/INSPIRE-61494ff5-6fad-11e8-b649-52540023a883_20230504-091802/services/1/PullResults/1341-1360/14.iso19139.xml
- https://inspire-geoportal.ec.europa.eu/resources/INSPIRE-106902a4-2bd0-11e9-a83c-52540023a883_20230505-072902/services/1/PullResults/151-200/25.iso19139.xml
