### ISSUE TITLE
HNAP's use of online resources descriptions

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#25]
This is a question, not a change request.

HNAP2.3 use an aggregation of 3 controlled fields for the description of online resources. It does not allow providing an actual description of the online resource in its description parameter. My questions:
1. Can we provide the description at another location in the output XML?
2. Is there a better way of specifying the HNAP-compliant description other than pushing it directly in the MCF file?

Here's an example of what HNAP2.3 wants as a description of an online resource: Web Service;WMS;eng

Thanks for your thoughts and comments -- Alex

**Comment by tomkralidis** [comment]
Fixed in master in #31. Implemented only for HNAP via `hnap_contenttype_en` and `hnap_contenttype_fr`.  @alexandreleroux can you update docs?

IMHO this is an exotic stretch of implementing this in ISO when there are already slots in the spec to support this properly.

**Comment by alexandreleroux** [comment]
Thanks Tom. There's something wrong in current pygeometa implementation. I get:
```
            <gmd:description xsi:type="gmd:PT_FreeText_PropertyType">
                <gco:CharacterString>Dataset;Autre;eng</gco:CharacterString>
                <gmd:PT_FreeText>
                  <gmd:textGroup>
                    <gmd:LocalisedCharacterString locale="#fra">Données;Autre;fra</gmd:LocalisedCharacterString>
                  </gmd:textGroup>
```
while it should ne "Dataset;Other;eng" on the second line. The MCF file is fine. Let me know if you need more details to fix this. Thanks -- Alex

**Comment by alexandreleroux** [comment]
there's now format_en and format_fr in pygeometa, this apparently fixes the latest issue. I'm leaving open until I update documentation accordingly

**Comment by alexandreleroux** [comment]
@tomkralidis this too would go in HNAP-schema.md, re https://github.com/geopython/pygeometa/issues/24#issuecomment-134682325 , agreed?

**Comment by tomkralidis** [comment]
:+1:

**Comment by alexandreleroux** [comment]
Updated doc in https://github.com/geopython/pygeometa/blob/master/doc/HNAP-schema.md and in the main reference doc, closing ticket. Thanks -- Alex
