### ISSUE TITLE
Generic design pattern to support multiple languages based on MCF parameters

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#33]
As discussed with @tomkralidis ; pygeometa's MCF parameters should support a generic design pattern for language. 

Example for the 'format' parameter: 
- given format, format_en, or format_fr
- if !format_en, then single lang output, else multiple lang

Same applies for all parameters (eg description, description_en, description_fr)

**Comment by tomkralidis** [comment]
@alexandreleroux implemented via #39.

**Comment by alexandreleroux** [comment]
Thanks. What's left before closing? There's at least updating the docs, anything else?

**Comment by tomkralidis** [comment]
I would say to ensure docs are updated accordingly.

**Comment by RousseauLambertLP** [comment]
This is documented in the "Sections" part of https://github.com/RousseauLambertLP/pygeometa/blob/master/doc/MCF_Reference.md Those keywords who require _en and _fr are identified in the tables.

Should we close the ticket?

**Comment by alexandreleroux** [comment]
Thanks @RousseauLambertLP . The intention here is to document the generic multiple language support in MCFs. What is currently documented is for _fr and _en. The goal is to let users know how to add their own language (e.g. _es for Spanish) in MCFs. Can you address this? Thanks!

**Comment by RousseauLambertLP** [comment]
Closing this issue, we have added and merged the documentation, see: https://github.com/geopython/pygeometa/blob/master/doc/MCF_Reference.md#multiple-languages-support
