### ISSUE TITLE
Missing xsd for HNAP

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#36]
Missing xsd for the HNAP schema.

```
<gmd:MD_Metadata xsi:schemaLocation="http://www.ec.gc.ca/data_donnees/standards/schemas/n
apec schema.xsd">
```

**Comment by tomkralidis** [comment]
@alexandreleroux actually this is better off as a post-processing step because napec is outside the scope of pygeometa.

**Comment by alexandreleroux** [comment]
Url http://www.ec.gc.ca/data_donnees/standards/schemas/napec schema.xsd is broken. ECDC is investigating.

**Comment by tomkralidis** [comment]
The schema is there:
http://www.ec.gc.ca/data_donnees/standards/schemas/napec/schema.xsd

**Comment by alexandreleroux** [comment]
yes, it's a typo they need to fix in the ECDC editor itself

**Comment by tomkralidis** [comment]
`xsi:schemaLocation` needs to be correctly crafted with the pattern `<namespace> <schema_location>`.  So a correct example would be:

`xsi:schemaLocation="http://www.ec.gc.ca/data_donnees/standards/schemas/napec  http://www.ec.gc.ca/data_donnees/standards/schemas/napec/schema.xsd"`

Of course just putitng `schema.xsd` implies that the XSD document is a relative path to the XML, which will usually break in a distributed computing platform/environment.

**Comment by alexandreleroux** [comment]
Indeed outside of pygeometa's scope, closing.
