### ISSUE TITLE
Website for pygeometa

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#4]
As discussed offline with @tomkralidis , we could eventually create a website for pygeometa (for docs, news via blog, etc). Could be hosted on http://geopython.github.io/pygeometa and leverage Jekyll. 

More discussions required before proceeding.

**Comment by samperd** [comment]
+1

**Comment by tomkralidis** [comment]
Website published to https://geopython.github.io/pygeometa

@alexandreleroux can we close?

**Comment by alexandreleroux** [comment]
Thanks a lot @tomkralidis !
