### ISSUE TITLE
MCF keyword substitution at run time (e.g. date)

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#52]
Feature request. It would be useful to have keywords in the MCF files to be substituted when pygeometa is ran.

As an example, if the keyword $date$ would be substituted by the actual datestamp at time of execution that would allow MCF files to require less modifications before generating XML files with pygeometa, thus less chances of errors.

Examples of where $date$ and $year$ keywords could be used in an MCF file:
- `datestamp=$date$` would become `datestamp=2016-09-13` at running time
- `rights_en=Copyright (c) $year$ Her Majesty the Queen in Right of Canada` would become `rights_en=Copyright (c) 2016 Her Majesty the Queen in Right of Canada`

**Comment by tomkralidis** [comment]
Implemented in master.  @alexandreleroux can you verify?

**Comment by alexandreleroux** [comment]
Thanks @tomkralidis Using this new substitution, I observe the following difference.

Without substitution:
```
  <gmd:dateStamp>
    <gco:Date>2016-09-13</gco:Date>
  </gmd:dateStamp>
```

With the substitution:
```
  <gmd:dateStamp>
    <gco:DateTime>2016-12-22T16:34:15Z</gco:DateTime>
  </gmd:dateStamp>
```

With the substitution, we go from 'date' to 'datetime'. If that's not a problem according to you, then let's close the issue. I'll add this in the documentation right away.
