### ISSUE TITLE
Support for not specifying a language for a dataset

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#55]
Request for supporting 'inapplicable' for [identification]:language values.

In the case where a dataset is made of numerical values, it makes sense for the dataset's language to be set to 'none' or its ISO19115 equivalent. pygeometa needs to support this value.

**Comment by tomkralidis** [comment]
Implemented in master using the `gco:nilReason` enumeration of:

- missing
- withheld
- inapplicable
- unknown
- template

@alexandreleroux please verify and add to docs.

**Comment by RousseauLambertLP** [comment]
[identification]:language values verified, they are used with `gco:nilReason`

Now we need to update the docs

**Comment by RousseauLambertLP** [comment]
Fixed in Merge request #96 , closing the issue.
