### ISSUE TITLE
Specifying the --output argument with the = sign in documentation

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#59]
Documentation currently indicate:
* `generate_metadata.py --mcf=path/to/file.mcf --schema_local=/path/to/my-schema --output some_file.xml`
which works, but for homogeneity, I'd suggest adding the `=` to `--output` and thus changing to 
* `generate_metadata.py --mcf=path/to/file.mcf --schema_local=/path/to/my-schema --output=some_file.xml`
which also works without any code change, only documentation would be slightly updated.

Agreed? Thx

**Comment by tomkralidis** [comment]
+1.
