### ISSUE TITLE
Test and fix 'mandatory' properties in MCF_Reference.md

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#65]
There are most probably errors in the [MCF_Reference.md](https://github.com/geopython/pygeometa/blob/master/doc/MCF_Reference.md) file regarding which properties are indeed mandatory when it comes localization.

Example, 'organization' is flagged as mandatory, but 'organization_en' and 'organization_fr' as well. Same for 'url', 'url_en' and 'url_fr'. I suggest that properties flagged as mandatory should be the ones indicated as such for the ISO19115:2003 schema.

Makes sense @tomkralidis ?

**Comment by tomkralidis** [comment]
👍 sounds good @alexandreleroux!

**Comment by alexandreleroux** [comment]
As far as I can see, elements needed to be fixed in MCF_Reference.md:
* identification
  * title
  * abstract
  * rights 
  * keywords
* contact
  * organization
* distribution
  * name 
  * description

**Comment by alexandreleroux** [comment]
thanks @RousseauLambertLP . Typo on L111 "Optinal", please fix, otherwise all fine :-)

**Comment by RousseauLambertLP** [comment]
Typo fixed in pull request. Thanks!
