### ISSUE TITLE
update base_mcf behaviour

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeometa#73]
cc @alexandreleroux 

Our current `base_mcf` support requires the base MCF to be a fully qualified MCF.  Update `base_mcf` support so that base MCF files are relative from where they are defined.  This results in, by design, MCF snippets which are not required to be fully qualified MCF files.  In addition, inheritence should continue to be supported (i.e. if value in base MCF and not in child MCF, then set; if in child and in base, override).

**Comment by tomkralidis** [comment]
Fixed in master.  Assigning to @alexandreleroux for docs.

**Comment by RousseauLambertLP** [comment]
Regarding the documentation on base_mcf behaviour, is this documentation enough: 

https://github.com/geopython/pygeometa/blob/master/doc/MCF_Reference.md#nesting-mcfs

Should we close the ticket?

**Comment by RousseauLambertLP** [comment]
But I think we should remove ```The base_mcf file must be in the same folder than the current MCF```

I don't think this is true anymore. For example, geomet MCF is not in the same folder as msc-nwp-gdps.yml and it works fine. 

If you want I can update the doc.

**Comment by alexandreleroux** [comment]
+1 to remove the "same folder" mention, that's not valid anymore, I'd also rephrase "In the case the user" to "In the case where the user", otherwise, sounds good to me to close this ticket :-) Thanks!
