### ISSUE TITLE
Expose pygeometa log messages when running from the command line

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#76]
Feature request to have pygeometa log messages to be exposed when running from the command line. The user should be able to specify the log level to output (e.g. info, warning, error, debug).

**Comment by tomkralidis** [comment]
@alexandreleroux implemented in master via #80.  Can you validate?

**Comment by RousseauLambertLP** [comment]
I tested ERROR, INFO and DEBUG, that all work fine. 

But I don't see where WARNING is used in the code...

**Comment by tomkralidis** [comment]
That's fine for now, and future proofs the CLI.

**Comment by alexandreleroux** [comment]
thanks @RousseauLambertLP for the validation and thanks @tomkralidis for the implementation! Closing ticket
