### ISSUE TITLE
Change variable name: #locale-fra to #fra

### ISSUE THREAD

**Issue by RousseauLambertLP** [geopython/pygeometa#77]
I tried to import some metadata xml files to ECDC but I get some errors. One of them is because we use a variable #locale-fra. 

Jose Garcia working on ECDC told me that we should use #fra instead. 

@tomkralidis @alexandreleroux should I update https://github.com/geopython/pygeometa/blob/master/pygeometa/templates/iso19139-hnap/main.j2 to output #fra?

**Comment by tomkralidis** [comment]
cc @josegar74

`#locale-fra` is just a pointer/label, so in theory any metadata parser should just follow this.  Regardless, updated in master to emit `#fra`.
