### ISSUE TITLE
language_alternate "fr" to "fra"

### ISSUE THREAD

**Issue by RousseauLambertLP** [geopython/pygeometa#78]
Our local variable for french in the yaml definition are "fr", but only "fra" is supported in ECDC. When generating the xml, some keywords are created with: 

* `<gmd:LocalisedCharacterString locale="#fr"`
instead of:
* `<gmd:LocalisedCharacterString locale="#fra"`

The result is that in ECDC, those keywords are not translated in french... 

I suggest we modify a little bit https://github.com/geopython/pygeometa/blob/master/pygeometa/templates/iso19139-hnap/main.j2#L202-205 . 

to:
```
{% else %}
  {% for kw1, kw2 in zip(keywords[0], keywords[1]) %}
    {% if record['metadata']['language_alternate'] == "fr" %}
      {% set language_alternate = "fra" %}
    {% endif %}
    {{ cs.get_freetext('keyword', language_alternate, [kw1, kw2]) }}
  {% endfor %}
{% endif %}
```
I think this is the easier solution. 

Other solution: 

* Modify another part of the script (more tricky)
* Change keywords_fr to keywords_fra in the yaml files
* Ask ECDC to support "fr" tag and "fra"

thoughts @tomkralidis @josegar74 ?

**Comment by tomkralidis** [comment]
@RousseauLambertLP : given `fra` is a hard HNAP requirement I've added a fix local to HNAP only for this case.  Can you validate against master?

**Comment by RousseauLambertLP** [comment]
I validated it and it works fine, closing the issue. 

Thanks @tomkralidis !
