### ISSUE TITLE
Import ISO metadata records into MCFs

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#79]
Feature request for pygeometa to be able to import ISO metadata records from external sources and create corresponding pygeometa MCF records in the yaml format.

Example use cases:
* help users create a first version of their existing metadata records in the pygeometa yaml MCF format, for those wanting to adopt pygeometa in their workflow
* allow users relying on metadata records in pygeometa's MCF format to automatically create MCFs from external sources

**Comment by tomkralidis** [comment]
Initial work started in https://github.com/geopython/pygeometa/tree/issue-79

**Comment by LM-HZG** [comment]
Hello there,
or group would be interested exactly in both the use cases described by @alexandreleroux. At first, we would like to be able to import XML encoded sample files to understand the structure and potential use of pygeometa and MCFs for our metadata publication workflows.

@tomkralidis Has there been any progress concerning this? Has this commit from the first of Nov. 2017 made it into the master branch and, thus, could it be tested?

**Comment by tomkralidis** [comment]
There hasn't been much progress, however contributions are welcome.  Note that any import to MCF type functionality from formal metadata standards will be lossy, but a full crawl of OWSLib's ISO object model will do the trick.

**Comment by pvgenuchten** [comment]
I wonder if we can use the jinja template to reverse engineer the metadata structure; like described at https://stackoverflow.com/questions/37813550/is-it-possible-to-use-a-jinja2-template-to-reverse-engineer-the-parameters-from

**Comment by tomkralidis** [comment]
FYI now implemented via #160.
