### ISSUE TITLE
On MCF parsing error, don't generate output XML

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#8]
Feature request. Currently, an empty XML output file is generated if pygeometa can't parse the whole MCF file because the MCF file contains syntax errors. Would be nice if the output XML file is written to file at the end of pygeometa's process, thus if pygeometa ends prematurely in a ParsingError, at least there won't be an empty file created.

This is different from feature request #5 which requires more code. Thanks -- Alex

**Comment by tomkralidis** [comment]
@alexandreleroux can you provide a minimal MCF that would yield syntax errors?

**Comment by alexandreleroux** [comment]
@tomkralidis Simply add a line that starts with '0' in the sample MCF. This will generate a syntax parsing error. Output XML will be created but empty.

**Comment by alexandreleroux** [comment]
Closing, after discussion with @tomkralidis , a better solution is described in feature request #9
