### ISSUE TITLE
Update $date$ in core.py

### ISSUE THREAD

**Issue by RousseauLambertLP** [geopython/pygeometa#81]
So $date$ in pygeometa creates a datetime representation. ECDC would like us to change our date format for publication: 
* "Publication date uses gco:DateTime, if the metadata is edited the value is lost as in ECCC metadata editor only is managing gco:Date. For FGP version this was updated, but was requested to not include in ECCC version. Please if you can create the metadata for now using gco:Date "

Should we update pygeometa’s magic $date$ as follows? :

* $date$ is a magic keyword for YYYY-MM-DD
* $datetime$$ is a magic keyword for YYYY-MM-DDTHH:MM:SSZ

**Comment by tomkralidis** [comment]
Thanks @RousseauLambertLP.  Fixed in master.  Can you validate and close if the fix works?

**Comment by tomkralidis** [comment]
Oops! Fixed now.
