### ISSUE TITLE
MCF version value for new YAML MCF format?

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#83]
In the pygeometa MCFs, there's a value for the MCF version as stated [in the documentation](https://github.com/geopython/pygeometa/blob/master/doc/MCF_Reference.md#sections):
```
mcf:
    version: 1.0.0
```

Given we changed the MCF format from INI to YAML, does it make sense to specify mcf.version: 2.0.0 now? Thanks. Copying @RousseauLambertLP

**Comment by tomkralidis** [comment]
+1 to default to 2.0.0, we should probably stick to x.y format (2.0) as a rule.

**Comment by alexandreleroux** [comment]
Agreed. Updating our local YAML MCFs. Leaving open until pygeometa documentation is updated

**Comment by tomkralidis** [comment]
I just realized pygeometa has never made it to a 1.0.0 release yet.  Should we keep the YAML version to 1.0 and assume the INI files were pre-1.0?  We don't have to follow YAML version with pygeometa version per se, but given the INI files were never versioned it may make sense. Thoughts?

**Comment by alexandreleroux** [comment]
Agreed. Let's revert our local MCF version to "1.0". Copying @rousseaulambertlp 

Furthermore, am I right that currently there isn't any validation of the MCF version value done when running pygeometa? There should be such a test that validates that the MCF version is indeed a supported version by pygeometa. If you agree, I'll create a new ticket accordingly. Merci

**Comment by tomkralidis** [comment]
@alexandreleroux agree and +1 for a new ticket on how to deal with mcf version checking and management.

**Comment by alexandreleroux** [comment]
Done and closing this one
