### ISSUE TITLE
MCF version validation before running pygeometa

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#85]
There should be a mechanism in pygeometa that validates that the MCF version stated in an input MCF file is indeed supported by pygeometa.

**Comment by tomkralidis** [comment]
Thanks @alexandreleroux.  Questions:

- MCF version is a *required* value, so if it's missing it's an error
- how do we manage MCF versions?  Suggest we support with pygeometa versions major versions
- what's the nature of the behaviour we're looking for? i.e.:
  - pygeometa manages versions in an n-1 fashion, i.e. its current version and the previous major version?
  - if a version is not supported do we throw error or warning and parse as best we can?

**Comment by alexandreleroux** [comment]
@tomkralidis good questions
* I confirm: if an MCF file doesn't state its version, then an error is provided
* Management of versions, when a new MCF version is created:
  * the sample.yml should be updated accordingly
  * pygeometa documentation should be updated accordingly
  * pygeometa should be tested against this new MCF version
  * if tests succeed, the next pygeometa release must support the new MCF version at the same time that the new MCF version specification is released 
* if pygeometa is being ran against an MCF version that is not supported, I agree with throwing an error and trying to parse nonetheless

It's still unclear how MCF versions will evolve. Maybe it will be worth later on to have a script that automatically update MCF files from one version to the latest one. We'll see with usage.

Makes sense?

**Comment by tomkralidis** [comment]
+1, will have something soon.

**Comment by tomkralidis** [comment]
Fixed in #87.  Documentation needs to be updated.

**Comment by RousseauLambertLP** [comment]
Looking at the code, mcf_versions is initialized twice (L154 and L224) and used only in line 226. 

I think we could remove one of the line where it's initialized. I tested it without line 154 and it works fine.

**Comment by tomkralidis** [comment]
Fixed thanks @RousseauLambertLP good catch!

**Comment by RousseauLambertLP** [comment]
I did a short version section in the MCF doc. 

See: 

https://github.com/RousseauLambertLP/pygeometa/blob/mcf-version-doc/doc/MCF_Reference.md#version

**Comment by alexandreleroux** [comment]
thanks @RousseauLambertLP , good work :-) Comments:
* typo: pygeometa doesn't have a capital P
* why do we state that pygeometa will support "previous major MCF versions"? I'm not certain we want that! :-)
* typo: sentence ends with a , instead of a .

**Comment by RousseauLambertLP** [comment]
I though from the previous comments that we wanted to support the previous (n-1) major version. We could removed it for now since we are at version 1...

**Comment by RousseauLambertLP** [comment]
Closing the issue, pygeometa validates MCF version and the doc was updated accordingly.
